'use client';

import React from 'react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  Cell,
} from 'recharts';

interface SourceItem {
  source: string;
  total: number;
  delivered: number;
  winRate: number;
}

export default function MarketingSourceBar({ data }: { data: SourceItem[] }) {
  return (
    <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs flex flex-col justify-between">
      <div>
        <div className="flex items-center justify-between mb-1">
          <h3 className="font-bold text-slate-900 text-sm">Marketing Acquisition Channels</h3>
          <span className="text-[11px] font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded">
            Volume & Win Rate
          </span>
        </div>
        <p className="text-xs text-slate-500 mb-4">
          Total inquiries generated by channel with win rate conversion
        </p>

        {/* Clean Horizontal Bar Chart */}
        <div className="h-56 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart
              data={data}
              layout="vertical"
              margin={{ top: 5, right: 35, left: 15, bottom: 5 }}
            >
              <XAxis type="number" hide />
              <YAxis
                type="category"
                dataKey="source"
                tick={{ fontSize: 11, fill: '#475569', fontWeight: 500 }}
                width={85}
              />
              <Tooltip
                formatter={(val: any, _: any, entry: any) => [
                  `${val} leads (${entry.payload.winRate}% won)`,
                  'Inquiries',
                ]}
                contentStyle={{
                  borderRadius: '8px',
                  fontSize: '12px',
                  borderColor: '#E2E8F0',
                }}
              />
              <Bar dataKey="total" radius={[0, 6, 6, 0]}>
                {data.map((item, index) => (
                  <Cell
                    key={`bar-${index}`}
                    // Channels with >25% win rate highlighted in primary blue; lower win rates use soft slate
                    fill={item.winRate >= 25 ? '#2563EB' : '#94A3B8'}
                  />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Conversion Footnote */}
      <div className="flex items-center justify-between text-[11px] text-slate-500 pt-3 border-t border-slate-100">
        <span className="flex items-center gap-1.5">
          <span className="w-2.5 h-2.5 rounded-full bg-blue-600 inline-block" />
          High Conversion Channel ($\ge$25%)
        </span>
        <span className="flex items-center gap-1.5">
          <span className="w-2.5 h-2.5 rounded-full bg-slate-400 inline-block" />
          Standard Conversion Channel
        </span>
      </div>
    </div>
  );
}